apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-shchpfxk-gitops
  description: This is GitOps manifest for go-shchpfxk   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=go-shchpfxk
    backstage.io/kubernetes-id: go-shchpfxk 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: go-shchpfxk
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-shchpfxk
